# set default settings
default:
  image:
    #this is my image created for this CI to use open-jdk with maven 
    name: s0nren/openjdk-maven:3.8.6-jdk21
    entrypoint: [""]

stages:
  - build
  - package

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

#{build stage to compile the back}
build:
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/movierizerapi-0.0.1-SNAPSHOT.jar

#TODO add the test stage to run the tests

#{package stage to build the docker image}
package:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: package
  before_script:
    - mkdir -p /kaniko/.docker
    - cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
  script: 
    - /kaniko/executor 
        --context "${CI_PROJECT_DIR}"
        --dockerfile Dockerfile 
        --destination "s0nren/movierizer-api:${API_VERSION}"
