FROM openjdk:21-jdk-slim AS builder

# Install required packages to the container
RUN apt-get update \
  && apt-get install -y ca-certificates curl git openssh-client --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

# Set environment variables for Maven 
ENV MAVEN_VERSION=3.8.8

# Install Maven
RUN curl -fsSL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xz -C /opt 



FROM openjdk:21-jdk-slim AS final

# Name for the image
LABEL org.opencontainers.image.title="Open-jdk Maven"
LABEL org.opencontainers.image.description="This image contains Open-jdk-21 and Maven version 3.8.6"

# Set environment variables for Maven 
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_VERSION=3.8.8
ENV PATH="${MAVEN_HOME}/bin:${PATH}"

COPY --from=builder opt/apache-maven-${MAVEN_VERSION} /opt/apache-maven-${MAVEN_VERSION}

RUN ln -s /opt/apache-maven-${MAVEN_VERSION} ${MAVEN_HOME} \
 && ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn


CMD ["mvn", "--version"]